GET http://localhost:3001

###

GET http://localhost:3001/info

###

GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/5fe51e2a3c64444b98bda8a4

###


DELETE http://localhost:3001/api/persons/63779c866d031540c476547b


###

POST http://localhost:3001/api/persons
content-type: application/json

{
  "name": "islam",
  "number":"077055555555"
}

###

POST http://localhost:3001/api/persons
content-type: application/json

{
  "name": "test",
  "number": "123456ffffff"
}

###

GET https://blooming-journey-91162.herokuapp.com/api/persons

###

PUT http://localhost:3001/api/persons/63779c866d031540c476547b
content-type: application/json

{
    "name": "islam",
    "number": "123456"
}
